# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Deploy to Looker
        if: github.event_name == 'push'
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"token": "${{ secrets.LOOKER_WEBHOOK_SECRET_PRODUCTION }}"}' \
            "https://nubalia.cloud.looker.com/webhooks/projects/pruebas_looker_sheila_prod/deploy"
